/**
 * Short HS chapter captions for “Filter by Goods” checkboxes (ellipsis-friendly).
 * Unknown chapters fall back to a generic phrase.
 */
const HS_CHAPTER_CAPTION: Record<number, string> = {
  1: "Live animals",
  2: "Meat and edible meat offal",
  3: "Fish, crustaceans, molluscs",
  4: "Dairy produce; birds' eggs; honey",
  5: "Products of animal origin n.e.s.",
  6: "Trees and other plants; bulbs; cut flowers",
  7: "Edible vegetables, roots and tubers",
  8: "Edible fruit and nuts; peel of citrus or melons",
  9: "Coffee, tea, maté and spices",
  10: "Cereals",
  11: "Milling industry products; malt; starches; gluten",
  12: "Oil seeds and oleaginous fruits",
  13: "Lac; gums, resins and other vegetable saps",
  14: "Vegetable plaiting materials",
  15: "Animal or vegetable fats and oils and waxes",
  16: "Preparations of meat, fish, crustaceans",
  17: "Sugars and sugar confectionery",
  18: "Cocoa and cocoa preparations",
  19: "Preparations of cereals, flour, starch or milk",
  20: "Preparations of vegetables, fruit, nuts",
  21: "Miscellaneous edible preparations",
  22: "Beverages, spirits and vinegar",
  23: "Residues and waste from food industries; prepared animal fodder",
  24: "Tobacco and manufactured tobacco substitutes",
  25: "Salt; sulphur; earths and stone; plastering materials",
  26: "Ores, slag and ash",
  27: "Mineral fuels, oils and products of their distillation",
  28: "Inorganic chemicals",
  29: "Organic chemicals",
  30: "Pharmaceutical products",
  31: "Fertilizers",
  32: "Tanning or dyeing extracts; paints; putty",
  33: "Essential oils and resinoids; perfumery, cosmetic",
  34: "Soap, washing prep., lubricating prep., waxes, candles",
  35: "Albuminoidal substances; modified starches; glues; enzymes",
  36: "Explosives; pyrotechnic products; matches",
  37: "Photographic or cinematographic goods",
  38: "Miscellaneous chemical products",
  39: "Plastics and articles thereof",
  40: "Rubber and articles thereof",
  41: "Raw hides and skins (other than furskins) and leather",
  42: "Articles of leather; saddlery; travel goods",
  43: "Furskins and artificial fur",
  44: "Wood and articles of wood; wood charcoal",
  45: "Cork and articles of cork",
  46: "Manufactures of straw, esparto or other plaiting materials",
  47: "Pulp of wood or fibrous cellulosic material; waste paper",
  48: "Paper and paperboard; articles of paper pulp",
  49: "Printed books, newspapers, pictures and other products",
  50: "Silk",
  51: "Wool, fine or coarse animal hair",
  52: "Cotton",
  53: "Other vegetable textile fibres; paper yarn",
  54: "Man-made filaments",
  55: "Man-made staple fibres",
  56: "Wadding, felt and nonwovens; special yarns; twine, cordage",
  57: "Carpets and other textile floor coverings",
  58: "Special woven fabrics; lace; tapestries; embroidery",
  59: "Impregnated, coated, covered or laminated textile fabrics",
  60: "Knitted or crocheted fabrics",
  61: "Articles of apparel and clothing accessories, knitted",
  62: "Articles of apparel and clothing accessories, not knitted",
  63: "Other made up textile articles; sets; worn clothing",
  64: "Footwear, gaiters and the like",
  65: "Headgear and parts thereof",
  66: "Umbrellas, sun umbrellas, walking-sticks, seat-sticks",
  67: "Prepared feathers and articles; artificial flowers",
  68: "Articles of stone, plaster, cement, asbestos, mica",
  69: "Ceramic products",
  70: "Glass and glassware",
  71: "Natural or cultured pearls, precious stones and metals",
  72: "Iron and steel",
  73: "Articles of iron or steel",
  74: "Copper and articles thereof",
  75: "Nickel and articles thereof",
  76: "Aluminum and articles thereof",
  77: "(Reserved)",
  78: "Lead and articles thereof",
  79: "Zinc and articles thereof",
  80: "Tin and articles thereof",
  81: "Other base metals; cermets; articles thereof",
  82: "Tools, implements, cutlery, spoons and forks, of base metal",
  83: "Miscellaneous articles of base metal",
  84: "Nuclear reactors, boilers, machinery and mechanical appliances",
  85: "Electrical machinery and equipment and parts thereof",
  86: "Railway or tramway locomotives, rolling-stock and parts",
  87: "Vehicles other than railway or tramway rolling-stock",
  88: "Aircraft, spacecraft, and parts thereof",
  89: "Ships, boats and floating structures",
  90: "Optical, photographic, measuring, checking, medical instruments",
  91: "Clocks and watches and parts thereof",
  92: "Musical instruments; parts and accessories",
  93: "Arms and ammunition; parts and accessories thereof",
  94: "Furniture; bedding, lighting, prefabricated buildings",
  95: "Toys, games and sports requisites; parts",
  96: "Miscellaneous manufactured articles",
  97: "Works of art, collectors' pieces and antiques",
};

export function formatHsChapterGoodsCheckboxLabel(chapterCode: string): string {
  const n = parseInt(chapterCode.replace(/^HS/i, ""), 10);
  if (Number.isNaN(n) || n < 1 || n > 97) return chapterCode;
  const cap = HS_CHAPTER_CAPTION[n] ?? `Goods under chapter ${n}`;
  return `${chapterCode} — ${cap}`;
}
